# Generated by Django 5.1.3 on 2024-11-05 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calcetin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=5.0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=100)),
                ('saldo', models.FloatField(default=0.0)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('C', 'Caixa'), ('B', 'BBVA'), ('U', 'UNICAJA'), ('I', 'ING')], max_length=10)),
                ('numero_cuenta', models.CharField(max_length=24)),
                ('creacion_cuenta', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banco_cliente', to='Calcetines.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_votacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('calcetin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='Calcetines.calcetin')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='Calcetines.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='valoracion',
            field=models.ManyToManyField(related_name='voto_cliente', through='Calcetines.Votacion', to='Calcetines.calcetin'),
        ),
    ]
